In [2]:
import numpy as np
import pandas as pd

In [3]:
pokemon = pd.read_csv('Pokemon.csv',sep=';',index_col=0)
pokemon.head()

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [4]:
print(pokemon.head(10))
print(pokemon.tail(3))

                        Name Type 1  Type 2  Total  HP  Attack  Defense  \
#
1                  Bulbasaur  Grass  Poison    318  45      49       49
2                    Ivysaur  Grass  Poison    405  60      62       63
3                   Venusaur  Grass  Poison    525  80      82       83
3      VenusaurMega Venusaur  Grass  Poison    625  80     100      123
4                 Charmander   Fire     NaN    309  39      52       43
5                 Charmeleon   Fire     NaN    405  58      64       58
6                  Charizard   Fire  Flying    534  78      84       78
6  CharizardMega Charizard X   Fire  Dragon    634  78     130      111
6  CharizardMega Charizard Y   Fire  Flying    634  78     104       78
7                   Squirtle  Water     NaN    314  44      48       65

   Sp. Atk  Sp. Def  Speed  Generation  Legendary
#
1       65       65     45           1      False
2       80       80     60           1      False
3      100      100     80           1      False
3      122      120     80           1      False
4       60       50     65           1      False
5       80       65     80           1      False
6      109       85    100           1      False
6      130       85    100           1      False
6      159      115    100           1      False
7       50       64     43           1      False
                    Name   Type 1 Type 2  Total  HP  Attack  Defense  Sp. Atk  \
#
720  HoopaHoopa Confined  Psychic  Ghost    600  80     110       60      150
720   HoopaHoopa Unbound  Psychic   Dark    680  80     160       60      170
721            Volcanion     Fire  Water    600  80     110      120      130

     Sp. Def  Speed  Generation  Legendary
#
720      130     70           6       True
720      130     80           6       True
721       90     70           6       True

In [5]:
type(pokemon)

pandas.core.frame.DataFrame

In [6]:
pokemon['Name']
type(pokemon['Name'])

pandas.core.series.Series

In [7]:
len(pokemon)

800

In [8]:
print(pokemon.columns)
print(pokemon.shape)

Index(['Name', 'Type 1', 'Type 2', 'Total', 'HP', 'Attack', 'Defense',
       'Sp. Atk', 'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')
(800, 12)

In [9]:
pokemon.Attack
pokemon['Defense']

#
1       49
2       63
3       83
3      123
4       43
      ...
719    150
719    110
720     60
720     60
721    120
Name: Defense, Length: 800, dtype: int64

In [10]:
pokemon[['Attack','Defense','HP']] #selecting multiple columns

     Attack  Defense  HP
#
1        49       49  45
2        62       63  60
3        82       83  80
3       100      123  80
4        52       43  39
..      ...      ...  ..
719     100      150  50
719     160      110  50
720     110       60  80
720     160       60  80
721     110      120  80

[800 rows x 3 columns]

In [11]:
pokemon[0:6] #returning the first 6 rows
pokemon[2:6] #will return rows 3-6

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False

In [12]:
pokemon.loc[4,'Name']
pokemon.iloc[4,1]

'Fire'

In [13]:
pokemon.loc[:100,"Type 1"]

#
1         Grass
2         Grass
3         Grass
3         Grass
4          Fire
         ...
96      Psychic
97      Psychic
98        Water
99        Water
100    Electric
Name: Type 1, Length: 109, dtype: object

In [14]:
pokemon.loc[:,'Name':'Type 2']

                      Name   Type 1  Type 2
#
1                Bulbasaur    Grass  Poison
2                  Ivysaur    Grass  Poison
3                 Venusaur    Grass  Poison
3    VenusaurMega Venusaur    Grass  Poison
4               Charmander     Fire     NaN
..                     ...      ...     ...
719                Diancie     Rock   Fairy
719    DiancieMega Diancie     Rock   Fairy
720    HoopaHoopa Confined  Psychic   Ghost
720     HoopaHoopa Unbound  Psychic    Dark
721              Volcanion     Fire   Water

[800 rows x 3 columns]

In [15]:
pokemon.loc[2:5,:]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False

In [16]:
pokemon["My favourite"]=False
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,My favourite
#,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True,False
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True,False
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True,False
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True,False
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True,False

In [17]:
del pokemon["My favourite"]
pokemon

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [18]:
pokemon["Attack"]<50 # it will give the boolean values of that series

#
1       True
2      False
3      False
3      False
4      False
       ...
719    False
719    False
720    False
720    False
721    False
Name: Attack, Length: 800, dtype: bool

In [19]:
pokemon[pokemon["Attack"]<50] #this is the exact way to get the values not the boolean one
pokemon[pokemon.Attack<50] #same shit

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
10,Caterpie,Bug,NaN,195,45,30,35,20,20,45,1,False
11,Metapod,Bug,NaN,205,50,20,55,25,25,30,1,False
12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
678,MeowsticMale,Psychic,NaN,466,74,48,76,83,81,104,6,False
678,MeowsticFemale,Psychic,NaN,466,74,48,76,83,81,104,6,False
684,Swirlix,Fairy,NaN,341,62,48,66,59,57,49,6,False
694,Helioptile,Electric,Normal,289,44,38,33,61,43,70,6,False
714,Noibat,Flying,Dragon,245,40,30,35,45,40,55,6,False

In [20]:
pokemon.loc[np.logical_and(pokemon["HP"]>70,pokemon["Attack"]<40)]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
113,Chansey,Normal,NaN,450,250,5,5,35,105,50,1,False
170,Chinchou,Water,Electric,330,75,38,38,56,56,67,2,False
174,Igglybuff,Normal,Fairy,210,90,30,15,40,20,15,2,False
202,Wobbuffet,Psychic,NaN,405,190,33,58,33,58,33,2,False
242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False
360,Wynaut,Psychic,NaN,260,95,23,48,23,48,23,3,False
440,Happiny,Normal,NaN,220,100,5,5,15,65,30,4,False
517,Munna,Psychic,NaN,292,76,25,45,67,55,24,5,False
555,DarmanitanZen Mode,Fire,Psychic,540,105,30,105,140,105,55,5,False

In [21]:
pokemon.loc[(pokemon["HP"]>70)&(pokemon['Attack']<200)]

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
717,Yveltal,Dark,Flying,680,126,131,95,131,98,99,6,True
718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [22]:
# how many pokemons are legendary
len(pokemon[pokemon["Legendary"]])

65

In [23]:
# What is the name of the first flying (Type 2) Pokemon which has a Speed of 60? Return only the Name of this pokemon.
pokemon.loc[(pokemon["Type 2"] == "Flying") & (pokemon["Speed"] == 60)].loc[83,"Name"]

"Farfetch'd"

In [24]:
#merging groups with variables

df = pokemon.loc[:6,:"Attack"]
df

                        Name Type 1  Type 2  Total  HP  Attack
#
1                  Bulbasaur  Grass  Poison    318  45      49
2                    Ivysaur  Grass  Poison    405  60      62
3                   Venusaur  Grass  Poison    525  80      82
3      VenusaurMega Venusaur  Grass  Poison    625  80     100
4                 Charmander   Fire     NaN    309  39      52
5                 Charmeleon   Fire     NaN    405  58      64
6                  Charizard   Fire  Flying    534  78      84
6  CharizardMega Charizard X   Fire  Dragon    634  78     130
6  CharizardMega Charizard Y   Fire  Flying    634  78     104

In [25]:
df1=pokemon.loc[:8,:"Speed"]
df1

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
#,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80
4,Charmander,Fire,NaN,309,39,52,43,60,50,65
5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80
6,Charizard,Fire,Flying,534,78,84,78,109,85,100
6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100
6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100
7,Squirtle,Water,NaN,314,44,48,65,50,64,43
8,Wartortle,Water,NaN,405,59,63,80,65,80,58

In [26]:
df2 = pokemon.loc[:9,"Attack":"Speed"]
df2

   Attack  Defense  Sp. Atk  Sp. Def  Speed
#
1      49       49       65       65     45
2      62       63       80       80     60
3      82       83      100      100     80
3     100      123      122      120     80
4      52       43       60       50     65
5      64       58       80       65     80
6      84       78      109       85    100
6     130      111      130       85    100
6     104       78      159      115    100
7      48       65       50       64     43
8      63       80       65       80     58
9      83      100       85      105     78
9     103      120      135      115     78

In [27]:
pd.concat([df1,df2])

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
#,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318.0,45.0,49,49,65,65,45
2,Ivysaur,Grass,Poison,405.0,60.0,62,63,80,80,60
3,Venusaur,Grass,Poison,525.0,80.0,82,83,100,100,80
3,VenusaurMega Venusaur,Grass,Poison,625.0,80.0,100,123,122,120,80
4,Charmander,Fire,NaN,309.0,39.0,52,43,60,50,65
5,Charmeleon,Fire,NaN,405.0,58.0,64,58,80,65,80
6,Charizard,Fire,Flying,534.0,78.0,84,78,109,85,100
6,CharizardMega Charizard X,Fire,Dragon,634.0,78.0,130,111,130,85,100
6,CharizardMega Charizard Y,Fire,Flying,634.0,78.0,104,78,159,115,100
7,Squirtle,Water,NaN,314.0,44.0,48,65,50,64,43
8,Wartortle,Water,NaN,405.0,59.0,63,80,65,80,58
1,NaN,NaN,NaN,NaN,NaN,49,49,65,65,45
2,NaN,NaN,NaN,NaN,NaN,62,63,80,80,60
3,NaN,NaN,NaN,NaN,NaN,82,83,100,100,80
3,NaN,NaN,NaN,NaN,NaN,100,123,122,120,80
4,NaN,NaN,NaN,NaN,NaN,52,43,60,50,65
5,NaN,NaN,NaN,NaN,NaN,64,58,80,65,80
6,NaN,NaN,NaN,NaN,NaN,84,78,109,85,100
6,NaN,NaN,NaN,NaN,NaN,130,111,130,85,100
6,NaN,NaN,NaN,NaN,NaN,104,78,159,115,100
7,NaN,NaN,NaN,NaN,NaN,48,65,50,64,43
8,NaN,NaN,NaN,NaN,NaN,63,80,65,80,58
9,NaN,NaN,NaN,NaN,NaN,83,100,85,105,78
9,NaN,NaN,NaN,NaN,NaN,103,120,135,115,78

our data frames are joined,but they do not appear to share any common data...for that we need to specify our axis
axis=0(Rows)
axis=1(Columns)

In [28]:
df3=pd.concat([df1,df2],axis=0)
df3

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
#,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318.0,45.0,49,49,65,65,45
2,Ivysaur,Grass,Poison,405.0,60.0,62,63,80,80,60
3,Venusaur,Grass,Poison,525.0,80.0,82,83,100,100,80
3,VenusaurMega Venusaur,Grass,Poison,625.0,80.0,100,123,122,120,80
4,Charmander,Fire,NaN,309.0,39.0,52,43,60,50,65
5,Charmeleon,Fire,NaN,405.0,58.0,64,58,80,65,80
6,Charizard,Fire,Flying,534.0,78.0,84,78,109,85,100
6,CharizardMega Charizard X,Fire,Dragon,634.0,78.0,130,111,130,85,100
6,CharizardMega Charizard Y,Fire,Flying,634.0,78.0,104,78,159,115,100
7,Squirtle,Water,NaN,314.0,44.0,48,65,50,64,43
8,Wartortle,Water,NaN,405.0,59.0,63,80,65,80,58
1,NaN,NaN,NaN,NaN,NaN,49,49,65,65,45
2,NaN,NaN,NaN,NaN,NaN,62,63,80,80,60
3,NaN,NaN,NaN,NaN,NaN,82,83,100,100,80
3,NaN,NaN,NaN,NaN,NaN,100,123,122,120,80
4,NaN,NaN,NaN,NaN,NaN,52,43,60,50,65
5,NaN,NaN,NaN,NaN,NaN,64,58,80,65,80
6,NaN,NaN,NaN,NaN,NaN,84,78,109,85,100
6,NaN,NaN,NaN,NaN,NaN,130,111,130,85,100
6,NaN,NaN,NaN,NaN,NaN,104,78,159,115,100
7,NaN,NaN,NaN,NaN,NaN,48,65,50,64,43
8,NaN,NaN,NaN,NaN,NaN,63,80,65,80,58
9,NaN,NaN,NaN,NaN,NaN,83,100,85,105,78
9,NaN,NaN,NaN,NaN,NaN,103,120,135,115,78

In [29]:

# df1 = pd.DataFrame({'A': [1, 2, 3]},index=[0,1,2])
# df2 = pd.DataFrame({'B': [4, 5,7]}, index=[0,1,2])
# df3=pd.concat([df1,df2],axis=1)
# df3

In [30]:
dfx=pd.read_csv("Pokemon.csv",sep=";",index_col=0)
dfx.head(10)

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False

In [31]:
poke1=dfx.loc[10:15,:"Speed"]
poke1

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
#,,,,,,,,,,
10,Caterpie,Bug,NaN,195,45,30,35,20,20,45
11,Metapod,Bug,NaN,205,50,20,55,25,25,30
12,Butterfree,Bug,Flying,395,60,45,50,90,80,70
13,Weedle,Bug,Poison,195,40,35,30,20,20,50
14,Kakuna,Bug,Poison,205,45,25,50,25,25,35
15,Beedrill,Bug,Poison,395,65,90,40,45,80,75
15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145

In [32]:
pd.concat([poke1,df3],axis=0)

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed
#,,,,,,,,,,
10,Caterpie,Bug,NaN,195.0,45.0,30,35,20,20,45
11,Metapod,Bug,NaN,205.0,50.0,20,55,25,25,30
12,Butterfree,Bug,Flying,395.0,60.0,45,50,90,80,70
13,Weedle,Bug,Poison,195.0,40.0,35,30,20,20,50
14,Kakuna,Bug,Poison,205.0,45.0,25,50,25,25,35
15,Beedrill,Bug,Poison,395.0,65.0,90,40,45,80,75
15,BeedrillMega Beedrill,Bug,Poison,495.0,65.0,150,40,15,80,145
1,Bulbasaur,Grass,Poison,318.0,45.0,49,49,65,65,45
2,Ivysaur,Grass,Poison,405.0,60.0,62,63,80,80,60
3,Venusaur,Grass,Poison,525.0,80.0,82,83,100,100,80
3,VenusaurMega Venusaur,Grass,Poison,625.0,80.0,100,123,122,120,80
4,Charmander,Fire,NaN,309.0,39.0,52,43,60,50,65
5,Charmeleon,Fire,NaN,405.0,58.0,64,58,80,65,80
6,Charizard,Fire,Flying,534.0,78.0,84,78,109,85,100
6,CharizardMega Charizard X,Fire,Dragon,634.0,78.0,130,111,130,85,100
6,CharizardMega Charizard Y,Fire,Flying,634.0,78.0,104,78,159,115,100
7,Squirtle,Water,NaN,314.0,44.0,48,65,50,64,43
8,Wartortle,Water,NaN,405.0,59.0,63,80,65,80,58
1,NaN,NaN,NaN,NaN,NaN,49,49,65,65,45
2,NaN,NaN,NaN,NaN,NaN,62,63,80,80,60
3,NaN,NaN,NaN,NaN,NaN,82,83,100,100,80
3,NaN,NaN,NaN,NaN,NaN,100,123,122,120,80
4,NaN,NaN,NaN,NaN,NaN,52,43,60,50,65
5,NaN,NaN,NaN,NaN,NaN,64,58,80,65,80
6,NaN,NaN,NaN,NaN,NaN,84,78,109,85,100
6,NaN,NaN,NaN,NaN,NaN,130,111,130,85,100
6,NaN,NaN,NaN,NaN,NaN,104,78,159,115,100
7,NaN,NaN,NaN,NaN,NaN,48,65,50,64,43
8,NaN,NaN,NaN,NaN,NaN,63,80,65,80,58
9,NaN,NaN,NaN,NaN,NaN,83,100,85,105,78
9,NaN,NaN,NaN,NaN,NaN,103,120,135,115,78

In [33]:
newdata=dfx.loc[:9,:]
newdata

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False
6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False
6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False
7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False

In [34]:
sadman = ['true','false','true','false','true','false','true','false','true','false','true','false','false']
newdata["sadman"]=sadman
newdata

/var/folders/76/z1mjvk1s7k36fwnyfkcvx1q40000gn/T/ipykernel_1483/3139044519.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdata["sadman"]=sadman

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,sadman
#,,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,true
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,false
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,true
3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False,false
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,true
5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,false
6,Charizard,Fire,Flying,534,78,84,78,109,85,100,1,False,true
6,CharizardMega Charizard X,Fire,Dragon,634,78,130,111,130,85,100,1,False,false
6,CharizardMega Charizard Y,Fire,Flying,634,78,104,78,159,115,100,1,False,true
7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False,false
8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False,true
9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False,false
9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False,false

In [35]:

pokemon["Attack2"]=pokemon["Attack"]+0.00 #it will be float instead of int
pokemon.dtypes

Name           object
Type 1         object
Type 2         object
Total           int64
HP              int64
Attack          int64
Defense         int64
Sp. Atk         int64
Sp. Def         int64
Speed           int64
Generation      int64
Legendary        bool
Attack2       float64
dtype: object

Date and time
any data type to do with dates and times always causes issues...there are just so many ways to represent this...and there are so many different timezones!!...all of this leads to one giant mess where it can be extremely hard to compare two times to each other...

In [36]:
pd.to_datetime('2026-2-17 09:10:12',format='%Y-%m-%d %H:%M:%S',utc=True)

Timestamp('2026-02-17 09:10:12+0000', tz='UTC')

In [38]:
#specifying timezone using tz_localize

pd.to_datetime("2014-12-3 09:10:12",format="%Y-%m-%d %H:%M:%S").tz_localize(tz="Europe/Brussels").astimezone("UTC")

Timestamp('2014-12-03 08:10:12+0000', tz='UTC')