# Chapter 3: Data exploration

In [92]:
import numpy as np
import pandas as pd

## 3.1 Introduction & Problem Setting

Today, you will tackle your very first data cleaning task! You will continue working on the Titanic dataset 🚢 and explore the many approaches you can use when cleaning a dataset. You will discover how each approach has its own advantages and disadvantages. Think of data cleaning like tidying up a messy room – different methods can help, but some are more effective than others!

## 3.2 Explore the content of the dataset

Load the Titanic dataset and start from the unmodified data. Explore the dataset and identify the following:

- How many records and columns do you have?
- How many columns contain missing values?
- How many columns do you want to transform?
- Which columns are these?

In [93]:
newdf = pd.read_csv("titanic_uncleaned.csv",sep=";")
newdf.describe()

       PassengerId      Pclass         Age       SibSp       Parch
count   892.000000  891.000000  714.000000  891.000000  891.000000
mean    446.500000    2.308642   29.706120    0.523008    0.381594
std     257.642517    0.836071   14.523986    1.102743    0.806057
min       1.000000    1.000000    0.420000    0.000000    0.000000
25%     223.750000    2.000000   20.125000    0.000000    0.000000
50%     446.500000    3.000000   28.000000    0.000000    0.000000
75%     669.250000    3.000000   38.000000    1.000000    0.000000
max     892.000000    3.000000   80.000000    8.000000    6.000000

In [94]:
newdf.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,No,3.0,"Braund, Mr. Owen Harris",male,NaN,1.0,0.0,A/5 21171,7.25,NaN,S
1,2,Yes,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,712.833,C85,C
2,3,Yes,3.0,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.925,NaN,S
3,4,Yes,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1,C123,S
4,5,No,3.0,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.05,NaN,S
5,6,No,3.0,"Moran, Mr. James",male,NaN,0.0,0.0,330877,84.583,NaN,Q
6,7,No,1.0,"McCarthy, Mr. Timothy J",male,54.0,0.0,0.0,17463,518.625,E46,S
7,8,No,3.0,"Palsson, Master. Gosta Leonard",male,2.0,3.0,1.0,349909,21.075,NaN,S
8,9,Yes,3.0,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0.0,2.0,347742,111.333,NaN,S
9,10,Yes,2.0,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1.0,0.0,237736,300.708,NaN,C

In [95]:
newdf.isna().sum()

PassengerId      0
Survived         1
Pclass           1
Name             1
Sex              0
Age            178
SibSp            1
Parch            1
Ticket           1
Fare             1
Cabin          688
Embarked         2
dtype: int64

## 3.3 Data transformations

Transform the data types of your columns! Make sure your data is in the desired form so you can easily handle the missing values later.

*Hint: We have not yet seen what to do with data in columns like 'Name', 'Ticket', and 'Cabin'. Thus, you can leave those three columns as they are.*

In [96]:
newdf.dtypes

PassengerId      int64
Survived        object
Pclass         float64
Name            object
Sex             object
Age            float64
SibSp          float64
Parch          float64
Ticket          object
Fare            object
Cabin           object
Embarked        object
dtype: object

In [97]:
newdf1 = pd.read_csv("titanic_uncleaned.csv",sep=";")
newdf1["Survived"]=newdf1["Survived"].map({"Yes": True,"No":False})
newdf1["Survived"].value_counts()

Survived
False    549
True     342
Name: count, dtype: int64

In [98]:
newdf1["Sex"]=newdf1["Sex"].map({"Male": True,"Female":False})
newdf1["Sex"].value_counts()

Series([], Name: count, dtype: int64)

In [101]:
newdf1=pd.get_dummies(newdf1,columns=["Embarked"])
newdf1
#newdf1.dtypes

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
0,1,False,3.0,"Braund, Mr. Owen Harris",NaN,NaN,1.0,0.0,A/5 21171,7.25,NaN,False,False,True
1,2,True,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",NaN,38.0,1.0,0.0,PC 17599,712.833,C85,True,False,False
2,3,True,3.0,"Heikkinen, Miss. Laina",NaN,26.0,0.0,0.0,STON/O2. 3101282,7.925,NaN,False,False,True
3,4,True,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",NaN,35.0,1.0,0.0,113803,53.1,C123,False,False,True
4,5,False,3.0,"Allen, Mr. William Henry",NaN,35.0,0.0,0.0,373450,8.05,NaN,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,888,True,1.0,"Graham, Miss. Margaret Edith",NaN,19.0,0.0,0.0,112053,30,B42,False,False,True
888,889,False,3.0,"Johnston, Miss. Catherine Helen \Carrie\""""",NaN,NaN,1.0,2.0,W./C. 6607,23.45,NaN,False,False,True
889,890,True,1.0,"Behr, Mr. Karl Howell",NaN,26.0,0.0,0.0,111369,30,C148,True,False,False
890,891,False,3.0,"Dooley, Mr. Patrick",NaN,32.0,0.0,0.0,370376,7.75,NaN,False,True,False
891,892,False,2.0,"Bracken, Mr. James H",NaN,27.0,0.0,0.0,220367,13,NaN,False,False,True

## 3.4 Missing values

Now it's time to tackle the missing values. First, check what you may have already done. Compare the current data with the raw dataset. Did you already solve some missing values?

In [104]:
newdf1.isna().sum()

PassengerId      0
Survived         1
Pclass           1
Name             1
Sex            892
Age            178
SibSp            1
Parch            1
Ticket           1
Fare             1
Cabin          688
Embarked_C       0
Embarked_Q       0
Embarked_S       0
dtype: int64

In [ ]:
newdf.isna().sum()

PassengerId      0
Survived         1
Pclass           1
Name             1
Sex              0
Age            178
SibSp            1
Parch            1
Ticket           1
Fare             1
Cabin          688
Embarked         2
dtype: int64

In [115]:
new_X = pd.read_csv("titanic_uncleaned.csv",sep=";")
new_X["Survived"]=new_X["Survived"].map({"Yes": True,"No":False})
new_X["Sex"]=new_X["Sex"].map({"male": True,"female":False})
new_X=pd.get_dummies(new_X,columns=["Embarked"])
new_X.isna().sum()

PassengerId      0
Survived         1
Pclass           1
Name             1
Sex              0
Age            178
SibSp            1
Parch            1
Ticket           1
Fare             1
Cabin          688
Embarked_C       0
Embarked_Q       0
Embarked_S       0
dtype: int64

In [ ]:
new_X["Survived"].unique()
new_X["Survived"]=new_X["Survived"].astype("bool")
new_X.dtypes

PassengerId      int64
Survived          bool
Pclass         float64
Name            object
Sex               bool
Age            float64
SibSp          float64
Parch          float64
Ticket          object
Fare            object
Cabin           object
Embarked_C        bool
Embarked_Q        bool
Embarked_S        bool
dtype: object

In [123]:
new_X.to_csv("Titanic_cleaned_exercise.csv")

Now it's time to get to work! Take a copy of your cleaned dataset and handle the missing values according to the three ways you've seen. Analyze and describe the effect each method has on the data. How many rows do you retain, how many columns? How good is the data quality? Can you think of ways to improve your approach?

### 3.4.1: Data removal

In [160]:
newdataframe1 = pd.read_csv("Titanic_cleaned_exercise.csv")
newdataframe1.head(10)
newdataframe1=newdataframe1.drop(columns=["Unnamed: 0"])
newdataframe1.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
143,144,False,3.0,"Burke, Mr. Jeremiah",True,19.00,0.0,0.0,365222,6.75,NaN,False,True,False
78,79,True,2.0,"Caldwell, Master. Alden Gates",True,0.83,0.0,2.0,248738,29,NaN,False,False,True
114,115,False,3.0,"Attalah, Miss. Malake",False,17.00,0.0,0.0,2627,144.583,NaN,True,False,False
243,244,False,3.0,"Maenpaa, Mr. Matti Alexanteri",True,22.00,0.0,0.0,STON/O 2. 3101275,7.125,NaN,False,False,True
13,14,False,3.0,"Andersson, Mr. Anders Johan",True,39.00,1.0,5.0,347082,31.275,NaN,False,False,True
191,192,False,2.0,"Carbines, Mr. William",True,19.00,0.0,0.0,28424,13,NaN,False,False,True
87,88,False,3.0,"Slocovski, Mr. Selman Francis",True,NaN,0.0,0.0,SOTON/OQ 392086,8.05,NaN,False,False,True
390,391,True,1.0,"Carter, Mr. William Ernest",True,36.00,1.0,2.0,113760,120,B96 B98,False,False,True
356,357,True,1.0,"Bowerman, Miss. Elsie Edith",False,22.00,0.0,1.0,113505,55,E33,False,False,True
513,514,True,1.0,"Rothschild, Mrs. Martin (Elizabeth L. Barrett)",False,54.00,1.0,0.0,PC 17603,59.4,NaN,True,False,False

In [161]:
newdataframe1.isna().sum()

PassengerId      0
Survived         0
Pclass           1
Name             1
Sex              0
Age            178
SibSp            1
Parch            1
Ticket           1
Fare             1
Cabin          688
Embarked_C       0
Embarked_Q       0
Embarked_S       0
dtype: int64

In [162]:
newdataframe1[newdataframe1["Pclass"].isna()]
newdataframe1=newdataframe1.drop(221)

In [163]:
newdataframe1=newdataframe1.drop_duplicates()

In [164]:
newdataframe1.reset_index()

,index,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
0,0,1,False,3.0,"Braund, Mr. Owen Harris",True,NaN,1.0,0.0,A/5 21171,7.25,NaN,False,False,True
1,1,2,True,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",False,38.0,1.0,0.0,PC 17599,712.833,C85,True,False,False
2,2,3,True,3.0,"Heikkinen, Miss. Laina",False,26.0,0.0,0.0,STON/O2. 3101282,7.925,NaN,False,False,True
3,3,4,True,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",False,35.0,1.0,0.0,113803,53.1,C123,False,False,True
4,4,5,False,3.0,"Allen, Mr. William Henry",True,35.0,0.0,0.0,373450,8.05,NaN,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,888,True,1.0,"Graham, Miss. Margaret Edith",False,19.0,0.0,0.0,112053,30,B42,False,False,True
887,888,889,False,3.0,"Johnston, Miss. Catherine Helen \Carrie\""""",False,NaN,1.0,2.0,W./C. 6607,23.45,NaN,False,False,True
888,889,890,True,1.0,"Behr, Mr. Karl Howell",True,26.0,0.0,0.0,111369,30,C148,True,False,False
889,890,891,False,3.0,"Dooley, Mr. Patrick",True,32.0,0.0,0.0,370376,7.75,NaN,False,True,False
890,891,892,False,2.0,"Bracken, Mr. James H",True,27.0,0.0,0.0,220367,13,NaN,False,False,True

In [165]:
newdataframe1.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            178
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked_C       0
Embarked_Q       0
Embarked_S       0
dtype: int64

### 3.4.2: Data Imputation

In [166]:
newdataframe1["Age"]

0       NaN
1      38.0
2      26.0
3      35.0
4      35.0
       ...
887    19.0
888     NaN
889    26.0
890    32.0
891    27.0
Name: Age, Length: 891, dtype: float64

In [167]:
newdataframe1["Age"].fillna(newdataframe1["Age"].mean())

0      29.709916
1      38.000000
2      26.000000
3      35.000000
4      35.000000
         ...
887    19.000000
888    29.709916
889    26.000000
890    32.000000
891    27.000000
Name: Age, Length: 891, dtype: float64

In [168]:
newdataframe1["Age"].fillna(newdataframe1["Age"].median())

0      28.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
887    19.0
888    28.0
889    26.0
890    32.0
891    27.0
Name: Age, Length: 891, dtype: float64

In [169]:
newdataframe1["Age"].fillna(newdataframe1["Age"].median())

0      28.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
887    19.0
888    28.0
889    26.0
890    32.0
891    27.0
Name: Age, Length: 891, dtype: float64

In [177]:
newdataframe1["Age"] = newdataframe1["Age"].ffill()
newdataframe1["Age"] = newdataframe1["Age"].bfill()

In [178]:
newdataframe1.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked_C       0
Embarked_Q       0
Embarked_S       0
dtype: int64

In [179]:
newdataframe1[newdataframe1["Age"].isna()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked_C, Embarked_Q, Embarked_S]
Index: []

### 3.4.3: Data Flagging

In [182]:
newdf['flag']=newdf["Age"].isna()
newdf

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,flag
0,1,No,3.0,"Braund, Mr. Owen Harris",male,NaN,1.0,0.0,A/5 21171,7.25,NaN,S,True
1,2,Yes,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,712.833,C85,C,False
2,3,Yes,3.0,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.925,NaN,S,False
3,4,Yes,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1,C123,S,False
4,5,No,3.0,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.05,NaN,S,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,888,Yes,1.0,"Graham, Miss. Margaret Edith",female,19.0,0.0,0.0,112053,30,B42,S,False
888,889,No,3.0,"Johnston, Miss. Catherine Helen \Carrie\""""",female,NaN,1.0,2.0,W./C. 6607,23.45,NaN,S,True
889,890,Yes,1.0,"Behr, Mr. Karl Howell",male,26.0,0.0,0.0,111369,30,C148,C,False
890,891,No,3.0,"Dooley, Mr. Patrick",male,32.0,0.0,0.0,370376,7.75,NaN,Q,False
891,892,No,2.0,"Bracken, Mr. James H",male,27.0,0.0,0.0,220367,13,NaN,S,False

### 3.5: Custom approach

Combine the knowledge you've gained by comparing the three methods to create one final cleaned dataset where all missing values are handled optimally!

In [213]:
new_custom = pd.read_csv("Titanic_uncleaned.csv",sep=";")

In [221]:
new_custom[new_custom["Pclass"].isna()]
# new_custom=new_custom.drop(221)
new_custom=new_custom.drop_duplicates()
new_custom=new_custom.reset_index()
new_custom=new_custom.drop(columns=["index"])
new_custom = pd.get_dummies(new_custom,columns=["Embarked"])
new_custom["Age"]=new_custom["Age"].ffill()
new_custom["Age"]=new_custom["Age"].bfill()

In [222]:
new_custom.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked_C       0
Embarked_Q       0
Embarked_S       0
dtype: int64