In [67]:
import pandas as pd
import numpy as np

1---data exploration

In [68]:
titanic_df=pd.read_csv('titanic_uncleaned.csv',sep=";")
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,No,3.0,"Braund, Mr. Owen Harris",male,NaN,1.0,0.0,A/5 21171,7.25,NaN,S
1,2,Yes,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,712.833,C85,C
2,3,Yes,3.0,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.925,NaN,S
3,4,Yes,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1,C123,S
4,5,No,3.0,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.05,NaN,S

In [69]:
titanic_df.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
882,883,No,3.0,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0.0,0.0,7552,105.167,NaN,S
883,884,No,2.0,"Banfield, Mr. Frederick James",male,28.0,0.0,0.0,C.A./SOTON 34068,10.5,NaN,S
884,885,No,3.0,"Sutehall, Mr. Henry Jr",male,25.0,0.0,0.0,SOTON/OQ 392076,7.05,NaN,S
885,886,No,3.0,"Rice, Mrs. William (Margaret Norton)",female,39.0,0.0,5.0,382652,29.125,NaN,Q
886,887,No,2.0,"Montvila, Rev. Juozas",male,27.0,0.0,0.0,211536,13,NaN,S
887,888,Yes,1.0,"Graham, Miss. Margaret Edith",female,19.0,0.0,0.0,112053,30,B42,S
888,889,No,3.0,"Johnston, Miss. Catherine Helen \Carrie\""""",female,NaN,1.0,2.0,W./C. 6607,23.45,NaN,S
889,890,Yes,1.0,"Behr, Mr. Karl Howell",male,26.0,0.0,0.0,111369,30,C148,C
890,891,No,3.0,"Dooley, Mr. Patrick",male,32.0,0.0,0.0,370376,7.75,NaN,Q
891,892,No,2.0,"Bracken, Mr. James H",male,27.0,0.0,0.0,220367,13,NaN,S

In [70]:
titanic_df.sample(10) #10 random rows

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
293,294,No,3.0,"Haas, Miss. Aloisia",female,24.00,0.0,0.0,349236,8.85,NaN,S
540,541,Yes,1.0,"Crosby, Miss. Harriet R",female,36.00,0.0,2.0,WE/P 5735,71,B22,S
182,183,No,3.0,"Asplund, Master. Clarence Gustaf Hugo",male,9.00,4.0,2.0,347077,313.875,NaN,S
92,93,No,1.0,"Chaffee, Mr. Herbert Fuller",male,46.00,1.0,0.0,W.E.P. 5734,61.175,E31,S
351,352,No,1.0,"Williams-Lambert, Mr. Fletcher Fellows",male,NaN,0.0,0.0,113510,35,C128,S
313,314,No,3.0,"Hendekovic, Mr. Ignjac",male,28.00,0.0,0.0,349243,78.958,NaN,S
520,521,Yes,1.0,"Perreault, Miss. Anne",female,30.00,0.0,0.0,12749,93.5,B73,S
676,677,No,3.0,"Sawyer, Mr. Frederick Charles",male,24.50,0.0,0.0,342826,8.05,NaN,S
469,470,Yes,3.0,"Baclini, Miss. Helene Barbara",female,0.75,2.0,1.0,2666,192.583,NaN,C
654,655,No,3.0,"Hegarty, Miss. Hanora \Nora\""""",female,18.00,0.0,0.0,365226,6.75,NaN,Q

In [71]:
titanic_df.describe()

       PassengerId      Pclass         Age       SibSp       Parch
count   892.000000  891.000000  714.000000  891.000000  891.000000
mean    446.500000    2.308642   29.706120    0.523008    0.381594
std     257.642517    0.836071   14.523986    1.102743    0.806057
min       1.000000    1.000000    0.420000    0.000000    0.000000
25%     223.750000    2.000000   20.125000    0.000000    0.000000
50%     446.500000    3.000000   28.000000    0.000000    0.000000
75%     669.250000    3.000000   38.000000    1.000000    0.000000
max     892.000000    3.000000   80.000000    8.000000    6.000000

In [72]:
titanic_df.dtypes

PassengerId      int64
Survived        object
Pclass         float64
Name            object
Sex             object
Age            float64
SibSp          float64
Parch          float64
Ticket          object
Fare            object
Cabin           object
Embarked        object
dtype: object

In [73]:
titanic_df.isna()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,True,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False
891,False,False,False,False,False,False,False,False,False,False,True,False

In [74]:
titanic_df.isna().describe()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,892,892,892,892,892,892,892,892,892,892,892,892
unique,1,2,2,2,1,2,2,2,2,2,2,2
top,False,False,False,False,False,False,False,False,False,False,True,False
freq,892,891,891,891,892,714,891,891,891,891,688,890

#2---transformation

In [75]:
titanic_df.Survived

0       No
1      Yes
2      Yes
3      Yes
4       No
      ...
887    Yes
888     No
889    Yes
890     No
891     No
Name: Survived, Length: 892, dtype: object

In [76]:
titanic_df["Survived"] = titanic_df["Survived"].map({'Yes':1,"No":0})
titanic_df["Survived"].value_counts()

Survived
0.0    549
1.0    342
Name: count, dtype: int64

In [77]:
titanic_df["Survived"].astype("bool")

0      False
1       True
2       True
3       True
4      False
       ...
887     True
888    False
889     True
890    False
891    False
Name: Survived, Length: 892, dtype: bool

In [78]:
titanic_df["Age"]

0       NaN
1      38.0
2      26.0
3      35.0
4      35.0
       ...
887    19.0
888     NaN
889    26.0
890    32.0
891    27.0
Name: Age, Length: 892, dtype: float64

In [79]:
#-data imputation
#-removing data
#-data flagging
new_Titanic_dataframe=titanic_df.dropna()
new_Titanic_dataframe
new_Titanic_dataframe.to_csv("Titanic_cleaned.csv")

In [80]:
age=titanic_df.bfill()
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3.0,"Braund, Mr. Owen Harris",male,NaN,1.0,0.0,A/5 21171,7.25,NaN,S
1,2,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,712.833,C85,C
2,3,1.0,3.0,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.925,NaN,S
3,4,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1,C123,S
4,5,0.0,3.0,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.05,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
887,888,1.0,1.0,"Graham, Miss. Margaret Edith",female,19.0,0.0,0.0,112053,30,B42,S
888,889,0.0,3.0,"Johnston, Miss. Catherine Helen \Carrie\""""",female,NaN,1.0,2.0,W./C. 6607,23.45,NaN,S
889,890,1.0,1.0,"Behr, Mr. Karl Howell",male,26.0,0.0,0.0,111369,30,C148,C
890,891,0.0,3.0,"Dooley, Mr. Patrick",male,32.0,0.0,0.0,370376,7.75,NaN,Q
891,892,0.0,2.0,"Bracken, Mr. James H",male,27.0,0.0,0.0,220367,13,NaN,S

In [81]:
new_Titanic_dataframe.describe()

       PassengerId    Survived      Pclass         Age       SibSp       Parch
count   183.000000  183.000000  183.000000  183.000000  183.000000  183.000000
mean    455.366120    0.672131    1.191257   35.674426    0.464481    0.475410
std     247.052476    0.470725    0.515187   15.643866    0.644159    0.754617
min       2.000000    0.000000    1.000000    0.920000    0.000000    0.000000
25%     263.500000    0.000000    1.000000   24.000000    0.000000    0.000000
50%     457.000000    1.000000    1.000000   36.000000    0.000000    0.000000
75%     676.000000    1.000000    1.000000   47.500000    1.000000    1.000000
max     890.000000    1.000000    3.000000   80.000000    3.000000    4.000000

In [82]:
titanic_df2=titanic_df.dropna(thresh=1)
titanic_df2.isna().describe()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,892,892,892,892,892,892,892,892,892,892,892,892
unique,1,2,2,2,1,2,2,2,2,2,2,2
top,False,False,False,False,False,False,False,False,False,False,True,False
freq,892,891,891,891,892,714,891,891,891,891,688,890

In [83]:
age=titanic_df["Age"].fillna(titanic_df['Age'].median())
print(age.value_counts())

Age
28.00    203
24.00     30
18.00     26
22.00     26
30.00     25
        ...
36.50      1
55.50      1
0.92       1
23.50      1
74.00      1
Name: count, Length: 88, dtype: int64

In [84]:
newdf = pd.read_csv("titanic_uncleaned.csv",sep=";")
newdf.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,No,3.0,"Braund, Mr. Owen Harris",male,NaN,1.0,0.0,A/5 21171,7.25,NaN,S
1,2,Yes,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,712.833,C85,C
2,3,Yes,3.0,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.925,NaN,S
3,4,Yes,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1,C123,S
4,5,No,3.0,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.05,NaN,S

In [85]:
newdf.sample(10) #will give 10 random columns so that we can explore the dataframe

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
827,828,Yes,2.0,"Mallet, Master. Andre",male,1.0,0.0,2.0,S.C./PARIS 2079,370.042,NaN,C
665,666,No,2.0,"Hickman, Mr. Lewis",male,32.0,2.0,0.0,S.O.C. 14879,73.5,NaN,S
787,788,No,3.0,"Rice, Master. George Hugh",male,8.0,4.0,1.0,382652,29.125,NaN,Q
209,210,Yes,1.0,"Blank, Mr. Henry",male,40.0,0.0,0.0,112277,31,A31,C
42,43,No,3.0,"Kraeff, Mr. Theodor",male,NaN,0.0,0.0,349253,78.958,NaN,C
73,74,No,3.0,"Chronopoulos, Mr. Apostolos",male,26.0,1.0,0.0,2680,144.542,NaN,C
515,516,No,1.0,"Walker, Mr. William Anderson",male,47.0,0.0,0.0,36967,340.208,D46,S
455,456,Yes,3.0,"Jalsevac, Mr. Ivan",male,29.0,0.0,0.0,349240,78.958,NaN,C
684,685,No,2.0,"Brown, Mr. Thomas William Solomon",male,60.0,1.0,1.0,29750,39,NaN,S
679,680,Yes,1.0,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0.0,1.0,PC 17755,5.123.292,B51 B53 B55,C

In [86]:
newdf.dtypes

PassengerId      int64
Survived        object
Pclass         float64
Name            object
Sex             object
Age            float64
SibSp          float64
Parch          float64
Ticket          object
Fare            object
Cabin           object
Embarked        object
dtype: object

In [87]:
newdf.describe() #this is to explore the dataset of statistical summaries.such as minimum value,maximum value,avg value and more!

       PassengerId      Pclass         Age       SibSp       Parch
count   892.000000  891.000000  714.000000  891.000000  891.000000
mean    446.500000    2.308642   29.706120    0.523008    0.381594
std     257.642517    0.836071   14.523986    1.102743    0.806057
min       1.000000    1.000000    0.420000    0.000000    0.000000
25%     223.750000    2.000000   20.125000    0.000000    0.000000
50%     446.500000    3.000000   28.000000    0.000000    0.000000
75%     669.250000    3.000000   38.000000    1.000000    0.000000
max     892.000000    3.000000   80.000000    8.000000    6.000000

In [88]:
newdf.isna() #isna gives a series of boolean in dataframe to identify the misssing values...if a place have values it will give false...and if a place doesnt have values it will give true

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,True,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False
891,False,False,False,False,False,False,False,False,False,False,True,False

In [89]:
newdf.isna().describe()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,892,892,892,892,892,892,892,892,892,892,892,892
unique,1,2,2,2,1,2,2,2,2,2,2,2
top,False,False,False,False,False,False,False,False,False,False,True,False
freq,892,891,891,891,892,714,891,891,891,891,688,890

Transforming data

In [90]:
newdf["Survived"]=newdf["Survived"].map({'No':0,'Yes':1}) #this will change yes to 1 and no to 0 in survived column...using map()...only works is one series not in full dataframe
newdf["Survived"]

0      0.0
1      1.0
2      1.0
3      1.0
4      0.0
      ...
887    1.0
888    0.0
889    1.0
890    0.0
891    0.0
Name: Survived, Length: 892, dtype: float64

In [91]:
newdf = pd.get_dummies(newdf,columns=["Embarked"])# this get_dummies will create a new columns for each possible values...like in a embarked there are three possible value which is c q s...so this function will create 3 columns as embarked_c embarked_s embarked_q...and there will be a boolean ans if that perticular value exist for the index and position

In [92]:
newdf.sample(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
89,90,0.0,3.0,"Celotti, Mr. Francesco",male,24.0,0.0,0.0,343275,8.05,NaN,False,False,True
759,760,1.0,1.0,"Rothes, the Countess. of (Lucy Noel Martha Dye...",female,33.0,0.0,0.0,110152,86.5,B77,False,False,True
173,174,0.0,3.0,"Sivola, Mr. Antti Wilhelm",male,21.0,0.0,0.0,STON/O 2. 3101280,7.925,NaN,False,False,True
163,164,0.0,3.0,"Calic, Mr. Jovo",male,17.0,0.0,0.0,315093,86.625,NaN,False,False,True
594,595,0.0,2.0,"Chapman, Mr. John Henry",male,37.0,1.0,0.0,SC/AH 29037,26,NaN,False,False,True

Missing values...there are three ways to handle missing data
-removing data
-data imputation
-data flagging

In [93]:
newdf

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
0,1,0.0,3.0,"Braund, Mr. Owen Harris",male,NaN,1.0,0.0,A/5 21171,7.25,NaN,False,False,True
1,2,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,712.833,C85,True,False,False
2,3,1.0,3.0,"Heikkinen, Miss. Laina",female,26.0,0.0,0.0,STON/O2. 3101282,7.925,NaN,False,False,True
3,4,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1,C123,False,False,True
4,5,0.0,3.0,"Allen, Mr. William Henry",male,35.0,0.0,0.0,373450,8.05,NaN,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,888,1.0,1.0,"Graham, Miss. Margaret Edith",female,19.0,0.0,0.0,112053,30,B42,False,False,True
888,889,0.0,3.0,"Johnston, Miss. Catherine Helen \Carrie\""""",female,NaN,1.0,2.0,W./C. 6607,23.45,NaN,False,False,True
889,890,1.0,1.0,"Behr, Mr. Karl Howell",male,26.0,0.0,0.0,111369,30,C148,True,False,False
890,891,0.0,3.0,"Dooley, Mr. Patrick",male,32.0,0.0,0.0,370376,7.75,NaN,False,True,False
891,892,0.0,2.0,"Bracken, Mr. James H",male,27.0,0.0,0.0,220367,13,NaN,False,False,True

In [94]:
newdf1 = newdf.dropna() #dropna removes any row containing atleadt one missing value...which can drastically remove the dataset size
newdf1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
1,2,1.0,1.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1.0,0.0,PC 17599,712.833,C85,True,False,False
3,4,1.0,1.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1.0,0.0,113803,53.1,C123,False,False,True
6,7,0.0,1.0,"McCarthy, Mr. Timothy J",male,54.0,0.0,0.0,17463,518.625,E46,False,False,True
10,11,1.0,3.0,"Sandstrom, Miss. Marguerite Rut",female,4.0,1.0,1.0,PP 9549,16.7,G6,False,False,True
11,12,1.0,1.0,"Bonnell, Miss. Elizabeth",female,58.0,0.0,0.0,113783,26.55,C103,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1.0,1.0,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1.0,1.0,11751,525.542,D35,False,False,True
872,873,0.0,1.0,"Carlsson, Mr. Frans Olof",male,33.0,0.0,0.0,695,5,B51 B53 B55,False,False,True
879,880,1.0,1.0,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0.0,1.0,11767,831.583,C50,True,False,False
887,888,1.0,1.0,"Graham, Miss. Margaret Edith",female,19.0,0.0,0.0,112053,30,B42,False,False,True
889,890,1.0,1.0,"Behr, Mr. Karl Howell",male,26.0,0.0,0.0,111369,30,C148,True,False,False

In [95]:
(newdf.isna().describe())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
count,892,892,892,892,892,892,892,892,892,892,892,892,892,892
unique,1,2,2,2,1,2,2,2,2,2,2,1,1,1
top,False,False,False,False,False,False,False,False,False,False,True,False,False,False
freq,892,891,891,891,892,714,891,891,891,891,688,892,892,892

In [96]:
(newdf1.isna().describe())

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
count,185,185,185,185,185,185,185,185,185,185,185,185,185,185
unique,1,1,1,1,1,1,1,1,1,1,1,1,1,1
top,False,False,False,False,False,False,False,False,False,False,False,False,False,False
freq,185,185,185,185,185,185,185,185,185,185,185,185,185,185

In [99]:
newdf3 = newdf.dropna(thresh=5) #atleast 5 missing values
newdf3.isna().describe()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
count,892,892,892,892,892,892,892,892,892,892,892,892,892,892
unique,1,2,2,2,1,2,2,2,2,2,2,1,1,1
top,False,False,False,False,False,False,False,False,False,False,True,False,False,False
freq,892,891,891,891,892,714,891,891,891,891,688,892,892,892

In [101]:
newdf["Age"].value_counts()

Age
24.00    30
22.00    26
18.00    26
28.00    25
19.00    25
         ..
36.50     1
55.50     1
0.92      1
23.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [ ]:
age = newdf["Age"].ffill() #this will fill the missing value with the previous last known value...if a position has 1 and after that position is empty or a missing value...ffill(forward fill) will fill the value with 1
age.value_counts()

Age
24.0    39
19.0    38
21.0    33
28.0    32
36.0    31
        ..
70.5     1
36.5     1
55.5     1
20.5     1
74.0     1
Name: count, Length: 88, dtype: int64

In [ ]:
age = newdf["Age"].bfill()#this will fill the missing value with the next known value...if a position has 1 and before that position is empty or a missing value...bfill(backword fill) will fill the value with 1
age.value_counts()

Age
24.00    38
18.00    35
25.00    30
28.00    30
22.00    30
         ..
0.67      1
55.50     1
0.42      1
34.50     1
74.00     1
Name: count, Length: 88, dtype: int64